// File generated by FlutterFire CLI.
// Run: flutterfire configure
// Replace these values with your actual Firebase project config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // ── REPLACE THESE VALUES WITH YOUR FIREBASE PROJECT CONFIG ──────────────
  // Go to: https://console.firebase.google.com → Project Settings → General
  // → Your apps → Add app (Android / iOS / Web) → copy config values below.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1TIwgDn4ecIgxkZ4KLbNdoscTWUx_SY',
    appId: '1:552723751219:web:967c6408efacfac1801e46',
    messagingSenderId: '552723751219',
    projectId: 'emp-management-40a60',
    authDomain: 'emp-management-40a60.firebaseapp.com',
    storageBucket: 'emp-management-40a60.firebasestorage.app',
    measurementId: 'G-EG6PGX0DNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-zwk_ZtRw5BbTwSbkHmgXv-VMgwu9y0',
    appId: '1:552723751219:android:0598b2aa4e71c37c801e46',
    messagingSenderId: '552723751219',
    projectId: 'emp-management-40a60',
    storageBucket: 'emp-management-40a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.employeeManagement',
  );
}